### ISSUE TITLE
Day/Night tarrif

### ISSUE THREAD

**Issue by danito** [myTselection/MyEnergy#11]
Hi,
I have a day/night meter and I would like to link the prices to your sensors, would it be possible to get them from the details?
That's my url:
[https://www.mijnenergie.be/energie-vergelijken-3-resultaten-?Form=fe&e=elektriciteit&d=1&c=particulier&cp=1190&i2=1----960-1400-0-1----1000----1-1%7C1%7C1%7C1-1600%7C690%7C1%7C%7C0%21V%21A%21n%7C0%21V%21A%7C0%7C3600%7C%7C%7C%7C%7C%21%7C%7C3600%7C%7C0-5%7C21-0](https://www.mijnenergie.be/energie-vergelijken-3-resultaten-?Form=fe&e=elektriciteit&d=1&c=particulier&cp=1190&i2=1----960-1400-0-1----1000----1-1%7C1%7C1%7C1-1600%7C690%7C1%7C%7C0%21V%21A%21n%7C0%21V%21A%7C0%7C3600%7C%7C%7C%7C%7C%21%7C%7C3600%7C%7C0-5%7C21-0)

```
Dagtarief | 18,58 c€/kWh | 960 kWh | € 178,37
Nachttarief | 14,68 c€/kWh | 1400 kWh | € 205,52
Bijdrage “hernieuwbare energie” | 1,96 c€/kWh | 2360 kWh | € 46,26
kWh injectie zonnepanelen “Dag/Normale uren“ | 8,77 c€/kWh | -1600 kWh | - € 140,32
kWh injectie zonnepanelen “Nacht/Daluren“ | 3,34 c€/kWh | -690 kWh | - € 23,05
```

While searching how you get the data, I found this:
```python 
#only first restult is needed, if all details are required, remove the break below
                    break
```
But what to do with this data, does it get into a attribute or a proper sensor?

**Comment by myTselection** [comment]
added option in 2.4.0 to have extra attribute fulldetail to add json detail
example to fetch dagtarief out of it:
`{{state_attr('sensor.myenergy_1190_electricity_fixed','fulldetail')[0].Dagtarief[0]}}`

**Comment by myTselection** [comment]
please note these rates won't integrate all costs and promotions
