### ISSUE TITLE
Apex Card

### ISSUE THREAD

**Issue by VenimK** [myTselection/MyEnergy#13]
been testing this in a Apex Card

`type: custom:apexcharts-card
experimental:
  color_threshold: true
graph_span: 23h
header:
  title: Electricity Prijzen Vandaag
  show: true
span:
  start: day
now:
  show: true
  label: Nu
series:
  - entity: sensor.myenergy_9120_electricity_variable
    type: column
    show:
      extremas: true
    float_precision: 3
    color_threshold:
      - value: 0
        color: '#186ddc'
      - value: 0.155
        color: '#04822e'
      - value: 0.2
        color: '#12A141'
      - value: 0.25
        color: '#79B92C'
      - value: 0.3
        color: '#C4D81D'
      - value: 0.35
        color: '#F3DC0C'
      - value: 0.4
        color: '#EFA51E'
      - value: 0.45
        color: '#E76821'
      - value: 0.5
        color: '#DC182F'
yaxis:
  - id: '1'
    align_to: 0.1
    decimals: 2
    apex_config:
      title:
        text: €/kWh
      tickAmount: 4
apex_config:
  xaxis:
    type: datetime
    tooltip:
      enabled: false
  tooltip:
    enabled: true
    x:
      show: true
    fixed:
      enabled: true
      position: topLeft
  chart:
    height: 320px
  grid:
    show: true
    borderColor: rgba(255,255,255,0.1)
`

[
<img width="481" alt="Scherm­afbeelding 2024-01-12 om 08 34 41" src="https://github.com/myTselection/MyEnergy/assets/666520/71bcc6e4-894b-4879-9782-0e7b0e885922">
](url)

**Comment by myTselection** [comment]
and the issue you have is?
negative value looks strange, but such issue would not be related to the graph you show, so I don't really understand what you need....
