### ISSUE TITLE
conversion error while retrieving electricity price

### ISSUE THREAD

**Issue by mistertix** [myTselection/MyEnergy#14]
Hello,
I got following error after installing this integration. I thtought first that it was due to the fact I put 0 in yearlly average consumption for electricity but after put a value it's still the same.
is it related to the config i put?
could I let  the 'yearlly average consumption' at 0 because I still have compensation for now?
thanks,

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:894
First occurred: 16:04:33 (28 occurrences)
Last logged: 16:11:03

Update for sensor.myenergy_1780_electricity_fixed fails
Update for sensor.myenergy_1780_electricity_variable fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 894, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1212, in async_device_update
    await self.async_update()
  File "/config/custom_components/myenergy/sensor.py", line 245, in async_update
    self._price = float(self._price.replace(',', '.'))/100
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '23.679.20'

**Comment by myTselection** [comment]
thx for feedback! I'll try to fix asap

**Comment by mistertix** [comment]
I put '2500' as yearly average consumption and it was working.
so error happen with low number and 0.
but I would like to use 0 as net consumption as I still have compensation for my solar panel.
and sometimes 'promotion' can cover a bit prosumer fees.
thanks

**Comment by myTselection** [comment]
should be fixed in R2.3.1
