### ISSUE TITLE
Update for sensor.myenergy_9000_gas_fixed fails

### ISSUE THREAD

**Issue by jahpster** [myTselection/MyEnergy#15]
HI,
I got following error after installing this integration. 

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:898
First occurred: 23:31:52 (56 occurrences)
Last logged: 23:38:40

Update for sensor.myenergy_9000_gas_fixed fails
Update for sensor.myenergy_9000_gas_variable fails
Update for sensor.myenergy_9000_electricity_fixed fails
Update for sensor.myenergy_9000_electricity_variable fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 898, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1216, in async_device_update
    await self.async_update()
  File "/config/custom_components/myenergy/sensor.py", line 228, in async_update
    for fueltype_name in self._contract_type_details.keys():
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by myTselection** [comment]
You seem to have requested a fixed or variable contract type, but no offer for that contract type might have been available.
added extra validation for such case and extra logging

**Comment by myTselection** [comment]
should be fixed in R2.3.1
If still an issue, please re-open or create a new incident
