### ISSUE TITLE
Missing energy supplier

### ISSUE THREAD

**Issue by tjorim** [myTselection/MyEnergy#4]
This is a nice integration, looks good for a first beta! However small remark: I see the contract name, but nothing indicates the energy supplier name. E.g. Luminus in the example below:
![Screenshot_20230926-152247.png](https://github.com/myTselection/MyEnergy/assets/1294876/75c45349-25d1-4644-b6f6-783419180797)

**Comment by myTselection** [comment]
aha, true. Well noticed. Will look into it for next release
