### ISSUE TITLE
Entity names acting up

### ISSUE THREAD

**Issue by tjorim** [myTselection/MyEnergy#8]
If I look at the device, all entities are named the same.

![Screenshot_20231006-063233.png](https://github.com/myTselection/MyEnergy/assets/1294876/3bd8cfc8-5ef8-4520-be39-ffad31ac5e42)

Clicking on it will show the full entity name.

![Screenshot_20231006-063228.png](https://github.com/myTselection/MyEnergy/assets/1294876/6c95bdf3-134f-4069-9da9-79bd6800f4a8)

I understand HA would automatically strip/show the name. More information here: https://developers.home-assistant.io/blog/2022/07/10/entity_naming?_highlight=has_entity_name

**Comment by myTselection** [comment]
thanks, I was able to fix it by now correctly setting the [device_info property](https://developers.home-assistant.io/docs/device_registry_index/)
